import Testing
import Foundation
@testable import RupuAPI

@Test func decodesAgentDefinitionsFixture() throws {
    let defs = try JSONDecoder().decode([AgentDefinition].self, from: Fixtures.data("agent_defs.json"))
    #expect(defs.count == 2)

    let reviewer = defs[0]
    #expect(reviewer.name == "code-reviewer")
    #expect(reviewer.slug == "code-reviewer")
    #expect(reviewer.description == "Reviews code for correctness and style")
    #expect(reviewer.provider == "anthropic")
    #expect(reviewer.model == "claude-sonnet-4-6")
    #expect(reviewer.effort == "Medium")
    #expect(reviewer.maxTokens == 8192)
    #expect(reviewer.mode == "ask")
    #expect(reviewer.tools == ["Read", "Grep", "Edit"])
    #expect(reviewer.scope == "global")
    #expect(reviewer.scopeKind == "global")
    #expect(reviewer.scopeID == nil)
    #expect(reviewer.runCount == 3)
    #expect(reviewer.lastRun == "2026-08-20T12:00:00+00:00")

    let triage = defs[1]
    #expect(triage.description == nil)
    #expect(triage.provider == nil)
    #expect(triage.model == nil)
    #expect(triage.effort == nil)
    #expect(triage.maxTokens == nil)
    #expect(triage.mode == nil)
    #expect(triage.tools == [])
    #expect(triage.scope == "widgets")
    #expect(triage.scopeKind == "project")
    #expect(triage.scopeID == "ws_a")
    #expect(triage.runCount == 0)
    #expect(triage.lastRun == nil)
}

@Test func decodesWorkflowDefinitionsFixture() throws {
    let defs = try JSONDecoder().decode([WorkflowDefinition].self, from: Fixtures.data("workflow_defs.json"))
    #expect(defs.count == 2)

    let nightly = defs[0]
    #expect(nightly.name == "nightly-health")
    #expect(nightly.scope == "global")
    #expect(nightly.scopeKind == "global")
    #expect(nightly.scopeID == nil)
    #expect(nightly.runCount == 5)
    #expect(nightly.lastRun == "2026-08-20T12:00:00+00:00")
    #expect(nightly.autoflowEnabled == true)

    let adhoc = defs[1]
    #expect(adhoc.name == "adhoc-build")
    #expect(adhoc.scopeID == "ws_a")
    #expect(adhoc.runCount == 0)
    #expect(adhoc.lastRun == nil)
    #expect(adhoc.autoflowEnabled == nil)
}

/// `GET /api/agents/:name` (Phase 5A, Task 7) — `AgentDetail` decodes the
/// flattened `AgentDetailDto` shape plus `systemPrompt`/`raw`, verified
/// against the real fixture generated by `agent_detail_fixture_is_current`
/// (`crates/rupu-cp/src/api/agents.rs`).
@Test func decodesAgentDetailFixture() throws {
    let detail = try JSONDecoder().decode(AgentDetail.self, from: Fixtures.data("agent_detail.json"))
    #expect(detail.name == "code-reviewer")
    #expect(detail.slug == "code-reviewer")
    #expect(detail.description == "Reviews code for correctness and style")
    #expect(detail.provider == "anthropic")
    #expect(detail.model == "claude-sonnet-4-6")
    #expect(detail.effort == "Medium")
    #expect(detail.maxTokens == 8192)
    #expect(detail.mode == "ask")
    #expect(detail.tools == ["Read", "Grep", "Edit"])
    #expect(detail.scope == "global")
    #expect(detail.scopeKind == "global")
    #expect(detail.scopeID == nil)
    #expect(detail.systemPrompt.contains("meticulous code reviewer"))
    #expect(detail.raw.hasPrefix("---\nname: code-reviewer"))
}

@Test func decodesWorkflowDetailFixtureWithBothInputs() throws {
    let detail = try JSONDecoder().decode(WorkflowDetail.self, from: Fixtures.data("workflow_detail.json"))
    #expect(detail.name == "nightly-health")
    #expect(detail.yaml.contains("name: nightly-health"))
    #expect(detail.inputs.count == 2)

    let branch = try #require(detail.inputs["branch"])
    #expect(branch.type == "string")
    #expect(branch.required)
    #expect(branch.default == nil)
    #expect(branch.allowedValues == ["main", "staging"])

    let target = try #require(detail.inputs["target"])
    #expect(target.type == "string")
    #expect(!target.required)
    #expect(target.default == "production")
    #expect(target.allowedValues == [])
}

@Test func decodesToolsFixtureIgnoringInputSchema() throws {
    let response = try JSONDecoder().decode(ToolsListResponse.self, from: Fixtures.data("tools.json"))
    #expect(response.tools.count == 2)
    #expect(response.tools[0].name == "scm.repos.list")
    #expect(response.tools[0].kind == "read")
    #expect(response.tools[1].name == "scm.branches.create")
    #expect(response.tools[1].kind == "write")
}

@Test func decodesAutoflowDefsFixture() throws {
    let defs = try JSONDecoder().decode([AutoflowDefinition].self, from: Fixtures.data("autoflow_defs.json"))
    #expect(defs.count == 2)

    let global = defs[0]
    #expect(global.name == "nightly-health")
    #expect(global.slug == "nightly-health")
    #expect(global.trigger == "cron")
    #expect(global.scope == "global")
    #expect(global.scopeKind == "global")
    #expect(global.scopeID == nil)
    #expect(global.enabled)

    // A DISABLED def is still listed (not filtered out), and its slug can
    // differ from its parsed name.
    let project = defs[1]
    #expect(project.name == "issue-triage")
    #expect(project.slug == "issue-triage-v2")
    #expect(project.trigger == "event")
    #expect(project.scope == "rupu")
    #expect(project.scopeKind == "project")
    #expect(project.scopeID == "ws-1")
    #expect(!project.enabled)
}

@Test func decodesWorkersFixtureWithFullAndEmptyCapabilities() throws {
    let rows = try JSONDecoder().decode([APIWorkerRow].self, from: Fixtures.data("workers.json"))
    #expect(rows.count == 2)

    let busy = rows[0]
    #expect(busy.workerID == "worker_local_team-mini_cli")
    #expect(busy.kind == "cli")
    #expect(busy.capabilities.backends == ["local_worktree"])
    #expect(busy.capabilities.scmHosts == ["github"])
    #expect(busy.capabilities.permissionModes == ["bypass", "readonly"])
    #expect(busy.activeRunCount == 2)
    #expect(busy.totalRunCount == 9)
    #expect(busy.lastRunAt == "2026-08-20T12:20:00Z")

    // `capabilities: {}` on the wire (every list empty via
    // `skip_serializing_if`) must still decode, defaulting each list to [].
    let idle = rows[1]
    #expect(idle.kind == "autoflow_serve")
    #expect(idle.capabilities.backends == [])
    #expect(idle.capabilities.scmHosts == [])
    #expect(idle.capabilities.permissionModes == [])
    #expect(idle.activeRunCount == 0)
    #expect(idle.totalRunCount == 0)
    #expect(idle.lastRunAt == nil)
}

@Test func decodesHostsFixtureWithVersionAndActiveRunCount() throws {
    let hosts = try JSONDecoder().decode([APIHostRow].self, from: Fixtures.data("hosts.json"))
    #expect(hosts.count == 3)

    let local = hosts[0]
    #expect(local.id == "local")
    #expect(local.version == "0.74.0")
    #expect(local.activeRunCount == 2)

    let mini = hosts[1]
    #expect(mini.activeRunCount == 0)
    #expect(mini.lastSeenAt == "2026-08-20T12:00:00Z")

    let kuki = hosts[2]
    #expect(kuki.status == "offline")
    #expect(kuki.version == nil)
    #expect(kuki.activeRunCount == 0)
}
