//! Renders `rupu-codename`'s crew tints and role badges as a TypeScript module
//! (`web/src/lib/codenamePalette.gen.ts`) so the web UI never hand-copies the
//! palette. A drift test keeps the committed file byte-identical to the render;
//! regenerate with `make cp-codename-palette`.

use rupu_codename::{role_badge, Shape, COLORS, ROLES};

fn shape_str(s: Shape) -> &'static str {
    match s {
        Shape::Circle => "circle",
        Shape::Triangle => "triangle",
        Shape::Square => "square",
        Shape::Diamond => "diamond",
        Shape::Pentagon => "pentagon",
        Shape::Hexagon => "hexagon",
        Shape::Star => "star",
        Shape::Cross => "cross",
        Shape::Ring => "ring",
        Shape::Chevron => "chevron",
        Shape::InvTriangle => "inv-triangle",
        Shape::Half => "half",
    }
}

/// Deterministic TS source (list order) for the generated palette module.
pub fn render_ts() -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by crates/rupu-cp/src/codename_palette.rs — do not edit.\n");
    out.push_str("// Regenerate: make cp-codename-palette\n");
    out.push_str("export type BadgeShape =\n");
    let shapes = [
        Shape::Circle,
        Shape::Triangle,
        Shape::Square,
        Shape::Diamond,
        Shape::Pentagon,
        Shape::Hexagon,
        Shape::Star,
        Shape::Cross,
        Shape::Ring,
        Shape::Chevron,
        Shape::InvTriangle,
        Shape::Half,
    ];
    for (i, s) in shapes.iter().enumerate() {
        let end = if i + 1 == shapes.len() { ";\n" } else { "\n" };
        out.push_str(&format!("  | '{}'{end}", shape_str(*s)));
    }
    out.push_str("export interface Tint {\n  light: string;\n  dark: string;\n}\n");
    out.push_str("export const CREW_TINTS: Record<string, Tint> = {\n");
    for (name, light, dark) in COLORS {
        out.push_str(&format!(
            "  {name}: {{ light: '{light}', dark: '{dark}' }},\n"
        ));
    }
    out.push_str("};\n");
    out.push_str("export const ROLE_BADGES: Record<string, { shape: BadgeShape } & Tint> = {\n");
    for role in ROLES {
        let b = role_badge(role);
        out.push_str(&format!(
            "  {role}: {{ shape: '{}', light: '{}', dark: '{}' }},\n",
            shape_str(b.shape),
            b.tint.light,
            b.tint.dark
        ));
    }
    out.push_str("};\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn codename_palette_ts_is_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("web/src/lib/codenamePalette.gen.ts");
        let rendered = render_ts();
        if std::env::var_os("REGEN_CODENAME_PALETTE").is_some() {
            std::fs::write(&path, &rendered).expect("write palette");
            return;
        }
        let on_disk = std::fs::read_to_string(&path)
            .expect("missing codenamePalette.gen.ts; run `make cp-codename-palette`");
        assert_eq!(
            on_disk, rendered,
            "codenamePalette.gen.ts drifted from rupu-codename; run `make cp-codename-palette`"
        );
    }

    #[test]
    fn render_covers_every_word() {
        let ts = render_ts();
        for (name, _, _) in rupu_codename::COLORS {
            assert!(ts.contains(&format!("  {name}: {{")));
        }
        for role in rupu_codename::ROLES {
            assert!(ts.contains(&format!("  {role}: {{")));
        }
    }
}
