//! Subcommand handlers. Each module owns one verb.

pub mod agent;
pub mod auth;
pub mod autoflow;
pub mod autoflow_runtime;
pub mod autoflow_wake;
pub mod cleanup;
pub mod completers;
pub mod completions;
pub mod config;
pub mod cron;
pub mod dispatch;
pub mod editor;
pub mod init;
pub mod issues;
pub mod mcp;
pub mod models;
pub mod repos;
pub mod retention;
pub mod run;
pub mod session;
pub mod transcript;
pub mod ui;
pub mod usage;
pub(crate) mod usage_report;
pub mod watch;
pub mod webhook;
pub mod workflow;
