#!/usr/bin/env python3
"""Generate the CLI reference from the binary's own `--help` output.

    scripts/gen-cli-reference.py [path/to/rupu] [--html OUT.html]

Writes docs/cli-reference.md (and, with --html, a rupu.sh docs page body
spliced into OUT.html between the CLI-REFERENCE markers). Every command,
argument and flag comes from clap, so the reference cannot drift from the
binary it was generated from — regenerate after changing the CLI.
"""
import html
import os
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GLOBAL_FLAGS = {"--format", "--absolute", "--all-columns", "--max-open-files", "-h, --help", "-V, --version", "--help", "--version"}
# `rupu run` parses its own argv (agent-first or a control verb), so clap's
# top-level help can't see its children; probe them explicitly.
RUN_CHILDREN = [("<agent>", ["run", "_agent_", "--help"]), ("pause", None), ("resume", None), ("list", None), ("show", None)]


def help_text(bin_, path):
    env = dict(os.environ, RUPU_HOME=tempfile.mkdtemp(), NO_COLOR="1", COLUMNS="10000")
    p = subprocess.run([bin_, *path], capture_output=True, text=True, env=env)
    return p.stdout or p.stderr


def parse(text):
    sections, cur, about = {}, None, []
    lines = text.splitlines()
    i = 0
    while i < len(lines) and not lines[i].startswith("Usage:"):
        if lines[i].strip():
            about.append(lines[i].strip())
        i += 1
    usage = lines[i][len("Usage: "):].strip() if i < len(lines) else ""
    for line in lines[i + 1:]:
        m = re.match(r"^([A-Z][A-Za-z ]+):$", line)
        if m:
            cur = m.group(1)
            sections[cur] = []
            continue
        if cur is None or not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        m = re.match(r"^\s+(\S.*?)(?:\s{2,}(.*))?$", line)
        if m and 2 <= indent <= 8:
            sections[cur].append([m.group(1).strip(), (m.group(2) or "").strip()])
        elif sections[cur]:
            sections[cur][-1][1] = (sections[cur][-1][1] + " " + line.strip()).strip()
    return {"about": " ".join(about), "usage": usage, **sections}


def walk(bin_, path, out):
    info = parse(help_text(bin_, [*path, "--help"]))
    info["path"] = path
    out.append(info)
    if path == ["run"]:
        for name, argv in RUN_CHILDREN:
            sub = parse(help_text(bin_, argv or ["run", name, "--help"]))
            sub["path"] = ["run", name]
            out.append(sub)
        return
    for name, _ in info.get("Commands", []):
        if name != "help":
            walk(bin_, [*path, name.split()[0]], out)


def opts(info):
    return [(f, d) for f, d in info.get("Options", []) if f.split(" <")[0] not in GLOBAL_FLAGS and f not in GLOBAL_FLAGS]


def anchor(path):
    return "rupu-" + "-".join(re.sub(r"[^a-z0-9-]+", "", p.lower()) or "agent" for p in path) if path else "rupu"


def md_escape(s):
    return s.replace("|", "\\|")


def to_md(cmds):
    top = cmds[0]
    out = [
        "# CLI reference",
        "",
        "<!-- Generated by scripts/gen-cli-reference.py from `rupu --help`; do not edit by hand. -->",
        "",
        "Every `rupu` command, argument and flag, generated from the binary's own help.",
        "Narrative guides live in [using-rupu.md](using-rupu.md) and the other docs.",
        "",
        "## Global options",
        "",
        "These apply to every command.",
        "",
        "| Option | Description |",
        "|---|---|",
    ]
    for f, d in top.get("Options", []):
        if f not in ("-h, --help", "-V, --version"):
            out.append(f"| `{f}` | {md_escape(d)} |")
    out += ["", "## Commands", ""]
    for c in cmds[1:]:
        depth = len(c["path"])
        out.append("  " * (depth - 1) + f"- [`rupu {' '.join(c['path'])}`](#{anchor(c['path'])})")
    for c in cmds[1:]:
        name = "rupu " + " ".join(c["path"])
        out += ["", f"<a id=\"{anchor(c['path'])}\"></a>", f"### `{name}`", ""]
        if c["about"]:
            out += [c["about"], ""]
        out += ["```", c["usage"], "```"]
        if c.get("Commands"):
            out += ["", "| Subcommand | Description |", "|---|---|"]
            for n, d in c["Commands"]:
                if n != "help":
                    out.append(f"| [`{n}`](#{anchor([*c['path'], n.split()[0]])}) | {md_escape(d)} |")
        if c.get("Arguments"):
            out += ["", "| Argument | Description |", "|---|---|"]
            out += [f"| `{a}` | {md_escape(d)} |" for a, d in c["Arguments"]]
        o = opts(c)
        if o:
            out += ["", "| Option | Description |", "|---|---|"]
            out += [f"| `{f}` | {md_escape(d)} |" for f, d in o]
    return "\n".join(out) + "\n"


def code_inline(s):
    s = html.escape(s)
    return re.sub(r"`([^`]+)`", r'<code class="inline">\1</code>', s)


def to_html(cmds):
    top = cmds[0]
    e = html.escape
    out = ['<!-- CLI-REFERENCE:BEGIN (generated by scripts/gen-cli-reference.py; do not edit by hand) -->',
           "<h2 id=\"global-options\">Global options</h2>",
           "<p>These apply to every command.</p>",
           "<table><thead><tr><th>Option</th><th>Description</th></tr></thead><tbody>"]
    for f, d in top.get("Options", []):
        if f not in ("-h, --help", "-V, --version"):
            out.append(f"<tr><td><code>{e(f)}</code></td><td>{code_inline(d)}</td></tr>")
    out.append("</tbody></table>")
    out.append("<h2 id=\"commands\">Commands</h2>")
    out.append("<table><thead><tr><th>Command</th><th>What it does</th></tr></thead><tbody>")
    for c in cmds[1:]:
        if len(c["path"]) == 1:
            out.append(f"<tr><td><a class=\"link\" href=\"#{anchor(c['path'])}\"><code>rupu {e(c['path'][0])}</code></a></td><td>{code_inline(c['about'])}</td></tr>")
    out.append("</tbody></table>")
    for c in cmds[1:]:
        name = "rupu " + " ".join(c["path"])
        tag = "h2" if len(c["path"]) == 1 else "h3"
        out.append(f"<{tag} id=\"{anchor(c['path'])}\"><code class=\"inline\">{e(name)}</code></{tag}>")
        if c["about"]:
            out.append(f"<p>{code_inline(c['about'])}</p>")
        out.append(f"<pre class=\"code\">{e(c['usage'])}</pre>")
        if c.get("Commands"):
            out.append("<table><thead><tr><th>Subcommand</th><th>Description</th></tr></thead><tbody>")
            for n, d in c["Commands"]:
                if n != "help":
                    out.append(f"<tr><td><a class=\"link\" href=\"#{anchor([*c['path'], n.split()[0]])}\"><code>{e(n)}</code></a></td><td>{code_inline(d)}</td></tr>")
            out.append("</tbody></table>")
        if c.get("Arguments"):
            out.append("<table><thead><tr><th>Argument</th><th>Description</th></tr></thead><tbody>")
            out += [f"<tr><td><code>{e(a)}</code></td><td>{code_inline(d)}</td></tr>" for a, d in c["Arguments"]]
            out.append("</tbody></table>")
        o = opts(c)
        if o:
            out.append("<table><thead><tr><th>Option</th><th>Description</th></tr></thead><tbody>")
            out += [f"<tr><td><code>{e(f)}</code></td><td>{code_inline(d)}</td></tr>" for f, d in o]
            out.append("</tbody></table>")
    out.append("<!-- CLI-REFERENCE:END -->")
    return "\n".join(out)


def main():
    args = sys.argv[1:]
    html_out = None
    if "--html" in args:
        i = args.index("--html")
        html_out = pathlib.Path(args[i + 1])
        del args[i:i + 2]
    bin_ = args[0] if args else str(ROOT / "target/debug/rupu")
    cmds = []
    walk(bin_, [], cmds)
    (ROOT / "docs/cli-reference.md").write_text(to_md(cmds))
    print(f"docs/cli-reference.md: {len(cmds) - 1} commands")
    if html_out:
        page = html_out.read_text()
        body = to_html(cmds)
        new, n = re.subn(r"<!-- CLI-REFERENCE:BEGIN.*?CLI-REFERENCE:END -->", lambda _m: body, page, flags=re.S)
        if n != 1:
            sys.exit(f"{html_out}: expected one CLI-REFERENCE marker block, found {n}")
        html_out.write_text(new)
        print(f"{html_out}: updated")


if __name__ == "__main__":
    main()
