# packaging/homebrew/rupu.rb is GENERATED from packaging/templates/rupu.rb.in
# by packaging/sync-community.sh. Edit the template; edits to the generated
# file are overwritten on every stable release.
#
# Homebrew formula for rupu. Consumes the published release binaries —
# building from source would need a pinned musl container and ~16 minutes.
class Rupu < Formula
  desc "Agentic code-development CLI"
  homepage "https://github.com/Section9Labs/rupu"
  version "0.71.0"
  license "Apache-2.0"

  # rupu shells out to `rg` and hard-errors without it. This is the
  # equivalent of the .deb's `Depends: ripgrep`.
  depends_on "ripgrep"

  on_macos do
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-darwin-arm64"
      sha256 "2fd131ae99933e83b5fef28df4936b30b71f0260bcf3ddab0f02b2909b4bf334"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-x64"
      sha256 "3c47a2079340be0a3bf91f5be6304d3a5b61e2b70c9a0b8368d88278719845e3"
    end
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-arm64"
      sha256 "42ea942c3917ff16d9f1a39d6a3e0a852b93bbddb975a2070e5507a0818acb01"
    end
  end

  def install
    # Exactly one asset is downloaded per platform (the `on_macos`/`on_linux`
    # blocks above select a single url). Assert that rather than trusting
    # `Dir["*"].first` — if a second entry ever appears, picking one at
    # random installs the wrong file under the name `rupu`.
    downloaded = Dir["*"]
    odie "expected exactly one downloaded asset, got: #{downloaded.inspect}" if downloaded.length != 1
    bin.install downloaded.first => "rupu"

    # `generate_completions_from_executable` can't express this binary's
    # CLI: rupu takes the shell name as a bare positional
    # (`completions print <shell>`) *and* needs `--static` appended after
    # it. Every built-in `shell_parameter_format` appends at most one
    # extra token (a flag, or the bare shell name, never both), so we
    # shell out explicitly instead — still generated by the binary
    # itself, just not via that helper.
    (bash_completion/"rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "bash", "--static")
    (zsh_completion/"_rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "zsh", "--static")
    (fish_completion/"rupu.fish").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "fish", "--static")

    (man1/"rupu.1").write Utils.safe_popen_read(bin/"rupu", "man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rupu --version")
    assert_match "linux-x64", shell_output("#{bin}/rupu update --print-platform") if OS.linux? && Hardware::CPU.intel?
  end
end
