# packaging/homebrew/rupu.rb is GENERATED from packaging/templates/rupu.rb.in
# by packaging/sync-community.sh. Edit the template; edits to the generated
# file are overwritten on every stable release.
#
# Homebrew formula for rupu. Consumes the published release binaries —
# building from source would need a pinned musl container and ~16 minutes.
class Rupu < Formula
  desc "Agentic code-development CLI"
  homepage "https://github.com/Section9Labs/rupu"
  version "0.75.0"
  license "Apache-2.0"

  # rupu shells out to `rg` and hard-errors without it. This is the
  # equivalent of the .deb's `Depends: ripgrep`.
  depends_on "ripgrep"

  on_macos do
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-darwin-arm64"
      sha256 "43aae599f7af2ea11c3777b6ce2b761e6667f647d88a33c7b81c921c228183c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-x64"
      sha256 "c0ea3ba77c357920d01a7f7a39d2b2968ff027da77513beb86534e09cb5b6a5d"
    end
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-arm64"
      sha256 "03195790af2f59e5f8d15a905f4c92a089866dbf22c519608bb12aa171d08ff6"
    end
  end

  def install
    # Exactly one asset is downloaded per platform (the `on_macos`/`on_linux`
    # blocks above select a single url). Assert that rather than trusting
    # `Dir["*"].first` — if a second entry ever appears, picking one at
    # random installs the wrong file under the name `rupu`.
    downloaded = Dir["*"]
    odie "expected exactly one downloaded asset, got: #{downloaded.inspect}" if downloaded.length != 1
    bin.install downloaded.first => "rupu"

    # `generate_completions_from_executable` can't express this binary's
    # CLI: rupu takes the shell name as a bare positional
    # (`completions print <shell>`) *and* needs `--static` appended after
    # it. Every built-in `shell_parameter_format` appends at most one
    # extra token (a flag, or the bare shell name, never both), so we
    # shell out explicitly instead — still generated by the binary
    # itself, just not via that helper.
    (bash_completion/"rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "bash", "--static")
    (zsh_completion/"_rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "zsh", "--static")
    (fish_completion/"rupu.fish").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "fish", "--static")

    (man1/"rupu.1").write Utils.safe_popen_read(bin/"rupu", "man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rupu --version")
    assert_match "linux-x64", shell_output("#{bin}/rupu update --print-platform") if OS.linux? && Hardware::CPU.intel?
  end
end
