# packaging/homebrew/rupu.rb is GENERATED from packaging/templates/rupu.rb.in
# by packaging/sync-community.sh. Edit the template; edits to the generated
# file are overwritten on every stable release.
#
# Homebrew formula for rupu. Consumes the published release binaries —
# building from source would need a pinned musl container and ~16 minutes.
class Rupu < Formula
  desc "Agentic code-development CLI"
  homepage "https://github.com/Section9Labs/rupu"
  version "0.77.0"
  license "Apache-2.0"

  # rupu shells out to `rg` and hard-errors without it. This is the
  # equivalent of the .deb's `Depends: ripgrep`.
  depends_on "ripgrep"

  on_macos do
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-darwin-arm64"
      sha256 "f95d48335183228fdc67eb4afab9e3069bc0dc75cd420ea2e049c0e1980b6623"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-x64"
      sha256 "2111da40699180cd8733787722097214baa0044c56af71ed168e6cc838a092f8"
    end
    on_arm do
      url "https://github.com/Section9Labs/rupu/releases/download/v#{version}/rupu-linux-arm64"
      sha256 "95d0348b48d74a8f23927afa56a83fcb24aa3965dda36f1e119afb97fcd0f421"
    end
  end

  def install
    # Exactly one asset is downloaded per platform (the `on_macos`/`on_linux`
    # blocks above select a single url). Assert that rather than trusting
    # `Dir["*"].first` — if a second entry ever appears, picking one at
    # random installs the wrong file under the name `rupu`.
    downloaded = Dir["*"]
    odie "expected exactly one downloaded asset, got: #{downloaded.inspect}" if downloaded.length != 1
    bin.install downloaded.first => "rupu"

    # `generate_completions_from_executable` can't express this binary's
    # CLI: rupu takes the shell name as a bare positional
    # (`completions print <shell>`) *and* needs `--static` appended after
    # it. Every built-in `shell_parameter_format` appends at most one
    # extra token (a flag, or the bare shell name, never both), so we
    # shell out explicitly instead — still generated by the binary
    # itself, just not via that helper.
    (bash_completion/"rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "bash", "--static")
    (zsh_completion/"_rupu").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "zsh", "--static")
    (fish_completion/"rupu.fish").write Utils.safe_popen_read(bin/"rupu", "completions", "print", "fish", "--static")

    (man1/"rupu.1").write Utils.safe_popen_read(bin/"rupu", "man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rupu --version")
    assert_match "linux-x64", shell_output("#{bin}/rupu update --print-platform") if OS.linux? && Hardware::CPU.intel?
  end
end
