#!/usr/bin/env node
// Extracts the ~30 lucide icons rupu.app uses out of the web app's `lucide-react` dependency and
// writes committed, SwiftUI-consumable assets:
//
//   RupuKit/Sources/RupuDesign/Icons/svg/<asset-name>.svg   — standalone 24×24 SVGs (audit/reference)
//   RupuKit/Sources/RupuDesign/Icons/svg/LICENSE-lucide.txt — ISC license + attribution
//   RupuKit/Sources/RupuDesign/Icons/LucideIconData.swift   — generated `LucideIconData.paths(for:)`
//
// Why: SwiftUI has no raw-SVG renderer, so every primitive (`circle`/`rect`/`line`/`polyline`/
// `polygon`/`ellipse`) is converted here, JS-side, into an SVG path `d` string — Swift's
// `SVGPathParser` only ever has to understand path data (`M/L/H/V/C/S/Q/T/A/Z`), never raw shape
// primitives. Circles/rounded-rect corners become `A` (arc) commands.
//
// Regeneration: run `node apps/rupu-macos/scripts/extract-lucide.mjs` from the repo root after
// `npm ci` in crates/rupu-cp/web (needed once, to populate node_modules/lucide-react). Output is
// deterministic — same lucide-react version in, byte-identical files out (icon order fixed below,
// no timestamps, numbers formatted with a fixed rounding rule) — so re-running with no lucide-react
// version bump produces a clean `git diff`.
//
// Filename note: lucide-react 0.468.0 kept a few pre-rename icons alive as alias modules that just
// re-export a renamed file's default export (e.g. `check-circle-2.js` -> `export { default } from
// './circle-check.js'`). Where that's the case, `source` below points at the CANONICAL file (the
// one with the actual element array) rather than the alias, while `asset` and the Swift enum case
// keep OUR name — web parity is by glyph, not by lucide's current filename. Every such remap is
// listed in the icon table's comments.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..", "..");
const lucideIconsDir = join(
  repoRoot,
  "crates/rupu-cp/web/node_modules/lucide-react/dist/esm/icons"
);
const lucideLicensePath = join(repoRoot, "crates/rupu-cp/web/node_modules/lucide-react/LICENSE");
const lucidePackageJsonPath = join(
  repoRoot,
  "crates/rupu-cp/web/node_modules/lucide-react/package.json"
);
const outDir = join(__dirname, "..", "RupuKit", "Sources", "RupuDesign", "Icons");
const svgDir = join(outDir, "svg");

if (!existsSync(lucideIconsDir)) {
  console.error(
    `lucide-react not found at ${lucideIconsDir}\n` +
      "Run `npm ci` in crates/rupu-cp/web first, then re-run this script."
  );
  process.exit(1);
}

// enumCase: the RupuKit `LucideIcon` case (Icon.swift — hand-written, not generated by this script;
//   keep the two in sync when editing this table).
// asset: kebab-case name used for the committed `svg/<asset>.svg` file.
// source: kebab-case lucide-react module (under dist/esm/icons/) whose element array we read.
//   Equal to `asset` except for the five documented alias remaps below.
const ICONS = [
  { enumCase: "layoutDashboard", asset: "layout-dashboard", source: "layout-dashboard" },
  { enumCase: "activity", asset: "activity", source: "activity" },
  { enumCase: "sparkles", asset: "sparkles", source: "sparkles" },
  { enumCase: "workflow", asset: "workflow", source: "workflow" },
  { enumCase: "repeatIcon", asset: "repeat", source: "repeat" },
  { enumCase: "messageSquare", asset: "message-square", source: "message-square" },
  { enumCase: "folderGit2", asset: "folder-git-2", source: "folder-git-2" },
  { enumCase: "folder", asset: "folder", source: "folder" },
  { enumCase: "shieldCheck", asset: "shield-check", source: "shield-check" },
  { enumCase: "shieldAlert", asset: "shield-alert", source: "shield-alert" },
  { enumCase: "network", asset: "network", source: "network" },
  { enumCase: "bookMarked", asset: "book-marked", source: "book-marked" },
  { enumCase: "server", asset: "server", source: "server" },
  { enumCase: "dollarSign", asset: "dollar-sign", source: "dollar-sign" },
  { enumCase: "settings", asset: "settings", source: "settings" },
  { enumCase: "radio", asset: "radio", source: "radio" },
  { enumCase: "play", asset: "play", source: "play" },
  // REMAP: check-circle-2.js is an alias re-exporting circle-check.js's default.
  { enumCase: "checkCircle2", asset: "check-circle-2", source: "circle-check" },
  // REMAP: x-circle.js is an alias re-exporting circle-x.js's default.
  { enumCase: "xCircle", asset: "x-circle", source: "circle-x" },
  { enumCase: "pause", asset: "pause", source: "pause" },
  // REMAP: pause-circle.js is an alias re-exporting circle-pause.js's default.
  { enumCase: "pauseCircle", asset: "pause-circle", source: "circle-pause" },
  // REMAP: x-octagon.js is an alias re-exporting octagon-x.js's default.
  { enumCase: "xOctagon", asset: "x-octagon", source: "octagon-x" },
  { enumCase: "ban", asset: "ban", source: "ban" },
  { enumCase: "skipForward", asset: "skip-forward", source: "skip-forward" },
  { enumCase: "clock", asset: "clock", source: "clock" },
  { enumCase: "arrowLeft", asset: "arrow-left", source: "arrow-left" },
  { enumCase: "archive", asset: "archive", source: "archive" },
  { enumCase: "trash2", asset: "trash-2", source: "trash-2" },
  { enumCase: "gitBranch", asset: "git-branch", source: "git-branch" },
  { enumCase: "listOrdered", asset: "list-ordered", source: "list-ordered" },
  { enumCase: "fileText", asset: "file-text", source: "file-text" },
  { enumCase: "chevronUp", asset: "chevron-up", source: "chevron-up" },
  { enumCase: "chevronDown", asset: "chevron-down", source: "chevron-down" },
  // REMAP: more-horizontal.js is an alias re-exporting ellipsis.js's default.
  { enumCase: "moreHorizontal", asset: "more-horizontal", source: "ellipsis" },
  { enumCase: "search", asset: "search", source: "search" },
  { enumCase: "lock", asset: "lock", source: "lock" },
  // Plan 3, Task 1: run-graph kind icons (RupuRunDetail's KindBridge). All five are direct
  // lucide-react 0.468.0 modules — no alias remaps needed.
  { enumCase: "bot", asset: "bot", source: "bot" },
  { enumCase: "columns3", asset: "columns-3", source: "columns-3" },
  { enumCase: "userCheck", asset: "user-check", source: "user-check" },
  { enumCase: "zap", asset: "zap", source: "zap" },
  { enumCase: "terminal", asset: "terminal", source: "terminal" },
  // Task 7: Workflow Builder kind visuals (split/join node icons).
  { enumCase: "split", asset: "split", source: "split" },
  { enumCase: "merge", asset: "merge", source: "merge" },
  // Task 10: Workflow Builder header's YAML-source toggle button.
  { enumCase: "code", asset: "code", source: "code" },
];

// --- number formatting: deterministic, minimal-digit output -----------------------------------

function fmt(n) {
  const rounded = Math.round(n * 1e6) / 1e6;
  // Avoid "-0".
  const normalized = rounded === 0 ? 0 : rounded;
  return String(normalized);
}

function num(v, fallback = 0) {
  if (v === undefined || v === null) return fallback;
  const n = typeof v === "number" ? v : parseFloat(v);
  return Number.isFinite(n) ? n : fallback;
}

// --- primitive -> path `d` conversion ----------------------------------------------------------

function circleToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const r = num(attrs.r);
  return ellipseArcsPath(cx, cy, r, r);
}

function ellipseToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const rx = num(attrs.rx);
  const ry = num(attrs.ry);
  return ellipseArcsPath(cx, cy, rx, ry);
}

// Two semicircle arcs, matching the exact shape SVGPathParserTests' arc-on-circle test parses.
function ellipseArcsPath(cx, cy, rx, ry) {
  const left = `${fmt(cx - rx)} ${fmt(cy)}`;
  const right = `${fmt(cx + rx)} ${fmt(cy)}`;
  return (
    `M${left}` +
    `A${fmt(rx)} ${fmt(ry)} 0 1 0 ${right}` +
    `A${fmt(rx)} ${fmt(ry)} 0 1 0 ${left}`
  );
}

function lineToPath(attrs) {
  const x1 = num(attrs.x1);
  const y1 = num(attrs.y1);
  const x2 = num(attrs.x2);
  const y2 = num(attrs.y2);
  return `M${fmt(x1)} ${fmt(y1)}L${fmt(x2)} ${fmt(y2)}`;
}

function pointsToPath(attrs, close) {
  const nums = attrs.points
    .trim()
    .split(/[\s,]+/)
    .map(Number);
  let d = "";
  for (let i = 0; i < nums.length; i += 2) {
    d += (i === 0 ? "M" : "L") + `${fmt(nums[i])} ${fmt(nums[i + 1])}`;
  }
  if (close) d += "Z";
  return d;
}

function rectToPath(attrs) {
  const x = num(attrs.x);
  const y = num(attrs.y);
  const w = num(attrs.width);
  const h = num(attrs.height);
  let rx = attrs.rx !== undefined ? num(attrs.rx) : attrs.ry !== undefined ? num(attrs.ry) : 0;
  let ry = attrs.ry !== undefined ? num(attrs.ry) : attrs.rx !== undefined ? num(attrs.rx) : 0;
  rx = Math.min(Math.max(rx, 0), w / 2);
  ry = Math.min(Math.max(ry, 0), h / 2);

  if (rx <= 0 || ry <= 0) {
    return `M${fmt(x)} ${fmt(y)}H${fmt(x + w)}V${fmt(y + h)}H${fmt(x)}Z`;
  }

  return [
    `M${fmt(x + rx)} ${fmt(y)}`,
    `H${fmt(x + w - rx)}`,
    `A${fmt(rx)} ${fmt(ry)} 0 0 1 ${fmt(x + w)} ${fmt(y + ry)}`,
    `V${fmt(y + h - ry)}`,
    `A${fmt(rx)} ${fmt(ry)} 0 0 1 ${fmt(x + w - rx)} ${fmt(y + h)}`,
    `H${fmt(x + rx)}`,
    `A${fmt(rx)} ${fmt(ry)} 0 0 1 ${fmt(x)} ${fmt(y + h - ry)}`,
    `V${fmt(y + ry)}`,
    `A${fmt(rx)} ${fmt(ry)} 0 0 1 ${fmt(x + rx)} ${fmt(y)}`,
    "Z",
  ].join("");
}

function elementToPath([tag, attrs]) {
  switch (tag) {
    case "path":
      return attrs.d;
    case "circle":
      return circleToPath(attrs);
    case "ellipse":
      return ellipseToPath(attrs);
    case "rect":
      return rectToPath(attrs);
    case "line":
      return lineToPath(attrs);
    case "polyline":
      return pointsToPath(attrs, false);
    case "polygon":
      return pointsToPath(attrs, true);
    default:
      throw new Error(`unsupported SVG primitive: ${tag}`);
  }
}

// --- reading lucide-react's element arrays -----------------------------------------------------

// lucide-react's per-icon modules look like:
//   const Clock = createLucideIcon("Clock", [
//     ["circle", { cx: "12", cy: "12", r: "10", key: "1mglay" }],
//     ["polyline", { points: "12 6 12 12 16 14", key: "68esgv" }]
//   ]);
// We pull out just the array-literal argument text and evaluate it in isolation (not the whole
// module — no import/export machinery involved). This is trusted local content (our own pinned
// node_modules dependency), not third-party input, so a plain `Function` eval is appropriate here.
function readElements(sourceName) {
  const path = join(lucideIconsDir, `${sourceName}.js`);
  if (!existsSync(path)) {
    throw new Error(`lucide-react module not found: ${path}`);
  }
  const text = readFileSync(path, "utf8");
  const start = text.indexOf("createLucideIcon(");
  if (start === -1) {
    throw new Error(`${sourceName}.js: no createLucideIcon(...) call found`);
  }
  const arrayStart = text.indexOf("[", start);
  if (arrayStart === -1) {
    throw new Error(`${sourceName}.js: no element array found after createLucideIcon(`);
  }
  let depth = 0;
  let i = arrayStart;
  for (; i < text.length; i++) {
    if (text[i] === "[") depth++;
    else if (text[i] === "]") {
      depth--;
      if (depth === 0) {
        i++;
        break;
      }
    }
  }
  const arrayText = text.slice(arrayStart, i);
  const elements = new Function(`return (${arrayText});`)();
  if (!Array.isArray(elements) || elements.length === 0) {
    throw new Error(`${sourceName}.js: parsed element array is empty`);
  }
  return elements;
}

// --- writing output ------------------------------------------------------------------------------

mkdirSync(svgDir, { recursive: true });

const swiftLicenseHeader = `// GENERATED FILE — do not edit by hand.
// Regenerate: node apps/rupu-macos/scripts/extract-lucide.mjs
// Source: lucide-react (see Icons/svg/LICENSE-lucide.txt for the ISC license + attribution).
`;

const caseEntries = [];

for (const { enumCase, asset, source } of ICONS) {
  const elements = readElements(source);
  const dStrings = elements.map(elementToPath);

  // Standalone .svg (24x24, lucide's own stroke conventions) for visual/audit review.
  const svgPaths = dStrings.map((d) => `  <path d="${d}"/>`).join("\n");
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" ` +
    `fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n` +
    `${svgPaths}\n</svg>\n`;
  writeFileSync(join(svgDir, `${asset}.svg`), svg);

  const pathLiterals = dStrings.map((d) => `                ${JSON.stringify(d)},`).join("\n");
  caseEntries.push(`        case .${enumCase}:\n            return [\n${pathLiterals}\n            ]`);
}

const swiftSwitch = caseEntries.join("\n");
const swiftSource = `${swiftLicenseHeader}
/// Per-icon SVG path \`d\` strings (24×24 viewBox), one entry per original lucide element —
/// \`SVGPathParser\` parses each into a \`CGPath\`; \`Icon\` strokes them all.
public enum LucideIconData {
    public static func paths(for icon: LucideIcon) -> [String] {
        switch icon {
${swiftSwitch}
        }
    }
}
`;
writeFileSync(join(outDir, "LucideIconData.swift"), swiftSource);

// LICENSE-lucide.txt: the ISC license text plus attribution of what was extracted from where.
const lucideLicenseText = readFileSync(lucideLicensePath, "utf8").trimEnd();
const lucideVersion = JSON.parse(readFileSync(lucidePackageJsonPath, "utf8")).version;
const attribution = `

---

The SVG files in this directory and the path data embedded in LucideIconData.swift are derived
from lucide-react ${lucideVersion} (https://lucide.dev), converted from JSX/primitive element
arrays into standalone SVG path data by apps/rupu-macos/scripts/extract-lucide.mjs.
`;
writeFileSync(join(svgDir, "LICENSE-lucide.txt"), `${lucideLicenseText}\n${attribution}`);

console.log(`Wrote ${ICONS.length} icons to ${svgDir}`);
console.log(`Wrote ${join(outDir, "LucideIconData.swift")}`);
